apiVersion: 1

datasources:
  - name: FlagForge Prometheus
    uid: flagforge-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
