apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flagforge-api.configMapName" . }}
  labels:
    {{- include "flagforge-api.labels" . | nindent 4 }}
data:
  ADMIN_RATE_LIMIT_REQUESTS: {{ .Values.runtime.adminRateLimitRequests | quote }}
  ADMIN_RATE_LIMIT_WINDOW_MS: {{ .Values.runtime.adminRateLimitWindowMs | quote }}
