apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flagforge-api.fullname" . }}
  labels:
    {{- include "flagforge-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "flagforge-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "flagforge-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.containerPort | quote }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "flagforge-api.secretName" . }}
                  key: {{ .Values.secret.keys.databaseUrl }}
            - name: ADMIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "flagforge-api.secretName" . }}
                  key: {{ .Values.secret.keys.adminApiKey }}
            - name: ADMIN_RATE_LIMIT_REQUESTS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "flagforge-api.configMapName" . }}
                  key: ADMIN_RATE_LIMIT_REQUESTS
            - name: ADMIN_RATE_LIMIT_WINDOW_MS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "flagforge-api.configMapName" . }}
                  key: ADMIN_RATE_LIMIT_WINDOW_MS
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
