{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flagforge-api.secretName" . }}
  labels:
    {{- include "flagforge-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secret.keys.databaseUrl }}: {{ .Values.secret.data.databaseUrl | quote }}
  {{ .Values.secret.keys.adminApiKey }}: {{ .Values.secret.data.adminApiKey | quote }}
{{- end }}
