apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flagforge-api-local
  namespace: argocd
  labels:
    app.kubernetes.io/name: flagforge-api
    app.kubernetes.io/part-of: flagforge
spec:
  project: default
  source:
    repoURL: https://github.com/dalloglio/flagforge.git
    targetRevision: main
    path: charts/flagforge-api
    helm:
      releaseName: flagforge-api
      valueFiles:
        - values-local.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: flagforge
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
